### ISSUE TITLE
Requisitos

### ISSUE THREAD

**Issue by fjaguero** [Gioyik/Addon-MH#10]
### Reuniones
- Crear nueva
- Ver Próximas
- Documentación
### Eventos
- Crear nuevo
- Ver Próximos
- Documentación
### Áreas
- Nombre área
  --> Responsable + Correo + Texto personalizado del áre
### Tareas
- Nom. Área --> Links
- Tareas sencillas
### Mentoría
- Emails Procedimientos
  ---> Recordatorios + Segundo contacto + Etc.
- Hoja de colaboradores

**Comment by marti1125** [comment]
supongo que la parte de que dice Documentación es un link...

**Comment by Gioyik** [comment]
@marti1125 creo que podrias trabajar en esto con @deibyod. Yo no le puedo dar continuidad completa fija al Addon y por ahora @deibyod parece estar mas que interesado en continuar con el proceso. Podemos usar este hilo para discutir la estructura basica del Addon y lo que se quiere en el. Usen este issue para que todo el mundo se vaya enterando.

**Comment by deibyod** [comment]
@Gioyik me parece bien!

**Comment by marti1125** [comment]
@Gioyik @deibyod ya no hay avance en el proyecto aun tienen planeado seguirlo.

**Comment by deibyod** [comment]
Hola @marti1125 como vas?, hace un tiempo le envié un plan de trabajo a @Gioyik , pero lamentablemente, como también le comentaba a el en un mensaje (pues es mi co-mentor), por cuestiones personales no podré trabajar un buen tiempo colaborando en cuestiones de Mozilla. Quizás si el te comparte la propuesta haya más interesados y puedan seguirle trabajando, a mi me sigue pareciendo muy importante y espero seguirle aportando cuando pueda volver a trabajar. Saludos!

**Comment by marti1125** [comment]
@fjaguero creo que cambiaron los requerimientos

**Comment by fjaguero** [comment]
Estos requerimientos los comentamos con @nukeador y Willy Aranda, podemos hablar por la lista para volver a definirlo.

**Comment by marti1125** [comment]
Me parece bien porque, han cambiado creo....

**Comment by fjaguero** [comment]
¿Y quién ha propuesto los cambios? ¿Sobre qué trata?

**Comment by fjaguero** [comment]
¿En qué estado está esto? ¿Se puede cerrar?

**Comment by marti1125** [comment]
yo creo si
